// <auto-generated />
using System;
using FootballGm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballGm.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808000907_ConfigureCompositeKeys")]
    partial class ConfigureCompositeKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<short>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("LosingScore")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<short>("WinningScore")
                        .HasColumnType("INTEGER");

                    b.Property<short>("WinningTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<short>("DraftYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("INTEGER");

                    b.Property<short>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<short>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.PlayerGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldGoalsAttempted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldGoalsMade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReturnedTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingFirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Sacks")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.PlayerSeason", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FieldGoalsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FieldGoalsMade")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReturnedTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingFirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Sacks")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "Season");

                    b.ToTable("PlayerSeasonStats");
                });
#pragma warning restore 612, 618
        }
    }
}
