// <auto-generated />
using System;
using FootballGm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballGm.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824013048_AddLeagueSettings")]
    partial class AddLeagueSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Associations.TeamPlayers", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "PlayerId", "ContractId");

                    b.HasIndex("ContractId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Budget", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentObligations")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId", "Week");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndWeek")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiftedCapSpace")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SigningBonus")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartWeek")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContractId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LeagueId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Rule", b =>
                {
                    b.Property<long>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RuleId");

                    b.HasIndex("SettingsId");

                    b.ToTable("Rules");

                    b.HasDiscriminator<short>("RuleType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("EligiblePositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeeklyCapSpace")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsId");

                    b.HasIndex("LeagueId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Loses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Ingested.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Temperature")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("WindSpeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Ingested.InjuryStatus", b =>
                {
                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialReportStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PracticePrimaryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PracticeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Season", "Week", "PlayerId");

                    b.ToTable("InjuryStatus");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Ingested.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<short>("DraftYear")
                        .HasColumnType("INTEGER");

                    b.Property<short>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Ingested.PlayerGame", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<short>("ExtraPointsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldGoalsMade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldGoalsMissed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReturnedTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingFirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Sacks")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("PlayerGame");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Ingested.PlayerSeason", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldGoalsMade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldGoalsMissed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReturnedTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingBrokenTackles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingFirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Sacks")
                        .HasColumnType("INTEGER");

                    b.Property<short>("TwoPointConversionsMade")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "Season");

                    b.ToTable("PlayerSeason");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.BonusRule", b =>
                {
                    b.HasBaseType("FootballGm.Api.Data.Entity.Contrived.Rule");

                    b.Property<decimal>("Points")
                        .HasColumnType("TEXT");

                    b.Property<short>("Stat")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Stat");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue((short)1);
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.ScoringWeightRule", b =>
                {
                    b.HasBaseType("FootballGm.Api.Data.Entity.Contrived.Rule");

                    b.Property<short>("Stat")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Stat");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue((short)0);
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Associations.TeamPlayers", b =>
                {
                    b.HasOne("FootballGm.Api.Data.Entity.Contrived.Contract", "Contract")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballGm.Api.Data.Entity.Ingested.Player", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballGm.Api.Data.Entity.Contrived.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Rule", b =>
                {
                    b.HasOne("FootballGm.Api.Data.Entity.Contrived.Settings", null)
                        .WithMany("Rules")
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Settings", b =>
                {
                    b.HasOne("FootballGm.Api.Data.Entity.Contrived.League", null)
                        .WithOne("Settings")
                        .HasForeignKey("FootballGm.Api.Data.Entity.Contrived.Settings", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Team", b =>
                {
                    b.HasOne("FootballGm.Api.Data.Entity.Contrived.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.RefreshToken", b =>
                {
                    b.HasOne("FootballGm.Api.Data.Entity.Contrived.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Contract", b =>
                {
                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.League", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Settings", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Contrived.Team", b =>
                {
                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Ingested.Player", b =>
                {
                    b.Navigation("TeamPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
