// <auto-generated />
using System;
using FootballGm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballGm.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812012628_digestionInfoTables")]
    partial class digestionInfoTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Temperature")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("WindSpeed")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.InjuryStatus", b =>
                {
                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialReportStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PracticePrimaryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PracticeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Season", "Week", "PlayerId");

                    b.ToTable("InjuryStatus");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<short>("DraftYear")
                        .HasColumnType("INTEGER");

                    b.Property<short>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.PlayerGame", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<short>("ExtraPointsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldGoalsMade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldGoalsMissed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReturnedTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingFirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Sacks")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("PlayerGame");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.PlayerSeason", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<short>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldGoalsMade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldGoalsMissed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingTwoPointConversions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("PassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ReturnedTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingBrokenTackles")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingFirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Sacks")
                        .HasColumnType("INTEGER");

                    b.Property<short>("TwoPointConversionsMade")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "Season");

                    b.ToTable("PlayerSeason");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FootballGm.Api.Data.Entity.RefreshToken", b =>
                {
                    b.HasOne("FootballGm.Api.Data.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
